Fix host files ownership
Elektrobit/ebcl_build_tools pull request #16
Opened 2024-11-06 14:04 UTC by thir820

# Changes

_(Provide a brief description of the changes in this pull request)_

# Dependencies:
_(Provide list of pull requests with dependecies with this pull request)_

# Tests results
```bash

```
# Developer Checklist:
- [ ] Test: Changes are tested
- [ ] Doc: Documentation has been updated 
- [ ] Git: Informative git commit message(s)
- [ ] Issue: If a related GitHub issue exists, linking is done

## Checklists for documentation
- [ ] Grammar: the content is grammatically correct
      (spelling, grammar, formatting, US English is used)
- [ ] Comprehensibility/Unambiguousness: the content is easy readable, clear to understand
- [ ] Correctness and consistency: the content is technically correct and consistent,
      no contradictions, no double descriptions
- [ ] Terminology: technical terms are clear and they are used correctly and documented in the glossary
- [ ] Level of detail: the content matches the detail level necessary for the reviewed object

# Reviewer checklist:
- [ ] Review: Changes are reviewed
- [ ] Review: Tested by the reviewer

## Checklists for documentation
- [ ] Grammar: the content is grammatically correct
      (spelling, grammar, formatting, US English is used)
- [ ] Comprehensibility/Unambiguousness: the content is easy readable, clear to understand
- [ ] Correctness and consistency: the content is technically correct and consistent,
      no contradictions, no double descriptions
- [ ] Terminology: technical terms are clear and they are used correctly and documented in the glossary
- [ ] Level of detail: the content matches the detail level necessary for the reviewed object
0 commit comments
Comments
0

2024-11-07 07:29 UTC, simone-weiss submitted a review, later dismissed

2024-11-07 08:15 UTC, MofX requested changes
And typo in commit message: "fix file ownership hanlding"

2024-11-07 08:15 UTC, MofX commented on ebcl/common/files.py
> +                # Create target directory if it not exists.
```suggestion
                # Create target directory if it does not exist
```

2024-11-07 08:15 UTC, MofX commented on ebcl/common/files.py
> +                    mode = mode[-3:]
```suggestion
                    mode = mode[-4:]
```
This keeps the suid, sgid and sticky bit as well

2024-11-07 08:15 UTC, MofX commented on tests/test_root.py
> +    @pytest.mark.skip(reason="Elbe not part of dev container anymore.")
```suggestion
    @pytest.mark.skip(reason="Elbe is not part of dev container anymore.")
```

2024-11-07 08:15 UTC, MofX commented on tests/test_root.py
> +    @pytest.mark.skip(reason="Elbe not part of dev container anymore.")
```suggestion
    @pytest.mark.skip(reason="Elbe is not part of dev container anymore.")
```

2024-11-07 10:51 UTC, thir820 commented
> And typo in commit message: "fix file ownership hanlding"

Yes, saw it too late.

2024-11-07 10:57 UTC, MofX commented
> > And typo in commit message: "fix file ownership hanlding"
> 
> Yes, saw it too late.

Just fix it using force-pushed. IMHO this PR shouldn't be squashed anyway (or squash merges in generally should never be used), because it renders the git history completely useless especially for unconnected commits like in this PR

2024-11-07 12:52 UTC, thir820 commented
> > > And typo in commit message: "fix file ownership hanlding"
> > 
> > 
> > Yes, saw it too late.
> 
> Just fix it using force-push. IMHO this PR shouldn't be squashed anyway (or squash merges in generally should never be used), because it renders the git history completely useless especially for unconnected commits like in this PR

I don't get this. No I have several commits for my changes and all the review findings, and the squash and merge will make one commit on main out of it. This makes sense for me, I and don't know why the separate commits of this PR should be preserved.

2024-11-07 13:21 UTC, MofX commented
> I don't get this. No I have several commits for my changes and all the review findings, and the squash and merge will make one commit on main out of it. This makes sense for me, I and don't know why the separate commits of this PR should be preserved.

A commit should be self-contained and do one job. When you squash this pr, the commit does not fulfil the second requirement anymore

And a commit message should describe what was changed. This is how every serious open source project uses git.
I don't want to preserve all the useless fixup commits, I suggest to always make changes, force push clean commits and then merge-commit or forward-merge the changes in the end. This way the commit history has value. With every other workflow the commit history and commit messages have no value at all (take a look at this useless commit message as an example:https://github.com/Elektrobit/ebcl_build_tools/commit/9483769aa215f0cc250a1fef16f846976b91dd0a)

2024-11-08 07:19 UTC, thir820 commented
> > I don't get this. No I have several commits for my changes and all the review findings, and the squash and merge will make one commit on main out of it. This makes sense for me, I and don't know why the separate commits of this PR should be preserved.
> 
> A commit should be self-contained and do one job. When you squash this pr, the commit does not fulfil the second requirement anymore
> 
> And a commit message should describe why something was changed. This is how every serious open source project uses git. I don't want to preserve all the useless fixup commits, I suggest to always make changes, force push clean commits and then merge-commit or forward-merge the changes in the end. This way the commit history has value. With every other workflow the commit history and commit messages have no value at all (take a look at this useless commit message as an example:[9483769](https://github.com/Elektrobit/ebcl_build_tools/commit/9483769aa215f0cc250a1fef16f846976b91dd0a))

It was done differently by now, but in general I agree. I did the squashing manually and force pushed.

2024-11-08 07:22 UTC, merged