EBLINUX-26937 use default gpg key for local type repo
Elektrobit/ebcl_build_tools pull request #25
Opened 2024-12-11 16:00 UTC by Ancord1

# Changes

When using local repo to add package to an image, it's required to provide gpg key in the yaml file. We want ebcl tooling to use locally generated gpg key implicitly, so there is no need to manually specify the key in the yaml config.

# Dependencies:
_(Provide list of pull requests with dependecies with this pull request)_

# Tests results
```bash

```
# Developer Checklist:
- [ ] Test: Changes are tested
- [ ] Doc: Documentation has been updated 
- [ ] Git: Informative git commit message(s)
- [ ] Issue: If a related GitHub issue exists, linking is done

## Checklists for documentation
- [ ] Grammar: the content is grammatically correct
      (spelling, grammar, formatting, US English is used)
- [ ] Comprehensibility/Unambiguousness: the content is easy readable, clear to understand
- [ ] Correctness and consistency: the content is technically correct and consistent,
      no contradictions, no double descriptions
- [ ] Terminology: technical terms are clear and they are used correctly and documented in the glossary
- [ ] Level of detail: the content matches the detail level necessary for the reviewed object

# Reviewer checklist:
- [ ] Review: Changes are reviewed
- [ ] Review: Tested by the reviewer

## Checklists for documentation
- [ ] Grammar: the content is grammatically correct
      (spelling, grammar, formatting, US English is used)
- [ ] Comprehensibility/Unambiguousness: the content is easy readable, clear to understand
- [ ] Correctness and consistency: the content is technically correct and consistent,
      no contradictions, no double descriptions
- [ ] Terminology: technical terms are clear and they are used correctly and documented in the glossary
- [ ] Level of detail: the content matches the detail level necessary for the reviewed object
0 commit comments
Comments
0

2024-12-13 08:21 UTC, simone-weiss reviewed
There are two things I would propose,

1) If no key is given and it is local, use trusted=yes configured in apt, maybe add a further config option as well for it

2) Here we have the problem because GNUPGHOME is not properly set. You could look where it is changed and ensure it is always /workspace/gpg-keys/.gnupg

2024-12-13 13:54 UTC, simone-weiss approved these changes

2024-12-23 09:32 UTC, simone-weiss approved these changes

2024-12-23 09:34 UTC, simone-weiss commented
Run # Run flake8 with settings from pyproject.yaml
./ebcl/common/apt.py:56:16: F821 undefined name 'key_gpg'
./ebcl/common/apt.py:56:39: F821 undefined name 'distro'
2     F821 undefined name 'key_gpg'
2

2024-12-23 09:34 UTC, simone-weiss requested changes
pls check flake

2025-01-27 09:29 UTC, thir820 commented
No response on review findings.

2025-01-27 09:29 UTC, closed without merging